### ISSUE TITLE
[TASK] Refactor and backup mobile

### ISSUE THREAD

**Issue by KamogeloMoeketse** [COS301-SE-2024/occupi#134]
**Task Request**

- [x] Delete occupi mobile 3
- [x] Create backup for occupi mobile 4
- [x] Find command to update backup on every push to dev (actions)

@KamogeloMoeketse , please tick off as you complete each task by clicking on the task you are done with in this comment
