### ISSUE TITLE
[TASK] Auth endpoint for resetting-password

### ISSUE THREAD

**Issue by waveyboym** [COS301-SE-2024/occupi#141]
**Task Request**

- [ ] Make endpoint to reset password
- [ ] Expect email to be sent to users address with a password reset link they can click on to reset their password(security)
- [ ] Make endpoint which expects new password and reset's correctly

@u21631532 , please tick off as you complete each task by clicking on the task you are done with in this comment

**Additional info**
Any additional info, articles that you think may help the developer should be added here.
