### ISSUE TITLE
[TASK]Send notification

### ISSUE THREAD

**Issue by KamogeloMoeketse** [COS301-SE-2024/occupi#146]
**Task Request**

- [ ] Do research on notification sending
- [ ] Send an example notification client side
- [ ] Send an example notification server side

@KamogeloMoeketse , please tick off as you complete each task by clicking on the task you are done with in this comment
