### ISSUE TITLE
[TASK] Cache database functions

### ISSUE THREAD

**Issue by waveyboym** [COS301-SE-2024/occupi#156]
**Task Request**

- [x] Add caching code to your database.go functions and write unit tests in tests/cache_test.go @u21631532 
- [x] Add caching code to your database.go functions and write unit tests in tests/cache_test.go @Rethakgetse-Manaka  
- [x] Add caching code to your database.go functions and write unit tests in tests/cache_test.go @waveyboym 

@u21631532, @Rethakgetse-Manaka, @waveyboym, please tick off as you complete each task by clicking on the task you are done with in this comment

**Additional info**
Please refactor all your database.go functions to follow the logic of this function: https://github.com/COS301-SE-2024/occupi/blob/develop/occupi-backend/pkg/database/database.go#L129-L156
1. check if the cache exists, if so, check if value exists for key and return it
2. if database is not initialized, return an error
3. proceed with normal database operations
4. save value with key in cache in case it might be accessed again

**note that by default, all key-value pairs will be evicted after 10 minutes have passed since inserting it into the cache
