### ISSUE TITLE
[FIX] login flow for mobile

### ISSUE THREAD

**Issue by KamogeloMoeketse** [COS301-SE-2024/occupi#168]
**Task Request**

- [ ] Use new login endpoint made for mobile
- [ ] Store token in expo secure storage
- [ ] Update profile details endpoint and logout enpoint to use the token as the auth header

@KamogeloMoeketse , please tick off as you complete each task by clicking on the task you are done with in this comment
