### ISSUE TITLE
[TASK] Begin Integration For Web

### ISSUE THREAD

**Issue by Tinashe-Austin** [COS301-SE-2024/occupi#176]
**Task Request**

- [ ] Request Relevant Endpoints Required for Integration
- [x] Integrate Login 
- [x] Integrate Dashboards/Overview Page
- [x] Integrate Profile Information 

<@Tinashe-Austin>, please tick off as you complete each task by clicking on the task you are done with in this comment

**Additional info**
Any additional info, articles that you think may help the developer should be added here.
