### ISSUE TITLE
[TASK] Begin Work for Data Visualization

### ISSUE THREAD

**Issue by Tinashe-Austin** [COS301-SE-2024/occupi#177]
**Task Request**

- [x] Request Relevant Information From Client For Data Visualization 
- [x] Research Relevant Graphs for Dashboard
- [x] Request Designs Based on Graphs
- [x] Begin Web Frontend Work For Data Visualization

<@Tinashe-Austin>, please tick off as you complete each task by clicking on the task you are done with in this comment

**Additional info**
Any additional info, articles that you think may help the developer should be added here.
