### ISSUE TITLE
[TASK] Increase tests coverage for backend

### ISSUE THREAD

**Issue by waveyboym** [COS301-SE-2024/occupi#185]
**Task Request**

- [x] @u21631532 write more unit tests, please look under additional info for more info
- [x] @Rethakgetse-Manaka write more unit tests, please look under additional info for more info
- [x] @waveyboym write more unit tests, please look under additional info for more info

@u21631532, @Rethakgetse-Manaka, @waveyboym, please tick off as you complete each task by clicking on the task you are done with in this comment

**Additional info**
make use of: https://app.codecov.io/gh/COS301-SE-2024/occupi/tree/develop/occupi-backend%2Fpkg to see which lines are hit and missed.
