### ISSUE TITLE
[TASK]Create Security Settings Page Mobile

### ISSUE THREAD

**Issue by KamogeloMoeketse** [COS301-SE-2024/occupi#192]
**Task Request**

- [x] Create security settings page to match figma wireframe
- [x] Add form validation to password fields
- [x] Link page to security settings in main settings page

@KamogeloMoeketse , please tick off as you complete each task by clicking on the task you are done with in this comment
