### ISSUE TITLE
[TASK] Responsiveness for Web

### ISSUE THREAD

**Issue by Tinashe-Austin** [COS301-SE-2024/occupi#196]
**Task Request**

- [ ] Make Login Responsive
- [ ] Make Top Nav Responsive
- [ ] Make Graphs Responsive
- [ ] Make all other pages Responsive

<@Tinashe-Austin>, please tick off as you complete each task by clicking on the task you are done with in this comment

**Additional info**
Any additional info, articles that you think may help the developer should be added here.
