### ISSUE TITLE
[TASK]Implement data processing for endpoint for Prediction models

### ISSUE THREAD

**Issue by Rethakgetse-Manaka** [COS301-SE-2024/occupi#202]
**Task Request**
Implement a function to process input for the prediction models

- [ ] Look at prediction model input shape
- [ ] Implement function to handle and post that input
- [ ] Process repsonse from model endpoint

@Rethakgetse-Manaka , please tick off as you complete each task by clicking on the task you are done with in this comment

**Additional info**
Any additional info, articles that you think may help the developer should be added here.
