### ISSUE TITLE
[TASK]Frontend cosmetic changes

### ISSUE THREAD

**Issue by KamogeloMoeketse** [COS301-SE-2024/occupi#210]
**Task Request**

- [ ] Navbar items should change colour depending on current tab
- [ ] Skeletons for Book page
- [ ] Skeletons for View Bookings Page

@KamogeloMoeketse , please tick off as you complete each task by clicking on the task you are done with in this comment

**Additional info**
Any additional info, articles that you think may help the developer should be added here.
