### ISSUE TITLE
[TASK]Notification Integration

### ISSUE THREAD

**Issue by KamogeloMoeketse** [COS301-SE-2024/occupi#236]
**Task Request**

- [ ] Retrieve data from api endpoint
- [ ] Sort the data in descending order and format the date correctly
- [ ] Divide the notifications into recent, yesterday and older

@KamogeloMoeketse , please tick off as you complete each task by clicking on the task you are done with in this comment
