### ISSUE TITLE
[TASK]Update settings integration

### ISSUE THREAD

**Issue by KamogeloMoeketse** [COS301-SE-2024/occupi#238]
**Task Request**

- [ ] Integration of updating notification settings
- [ ] Integration of updating security settings
- [ ] Integration of changing password

@KamogeloMoeketse , please tick off as you complete each task by clicking on the task you are done with in this comment
