### ISSUE TITLE
[TASK]Create appearance page settings

### ISSUE THREAD

**Issue by KamogeloMoeketse** [COS301-SE-2024/occupi#260]
**Task Request**

- [ ] Create page for the appearance settings according to figma
- [ ] Page should have states fro the accent colours as well as the theme
- [ ] Page should have otion for setting custom accent colour

@KamogeloMoeketse , please tick off as you complete each task by clicking on the task you are done with in this comment

**Additional info**
Any additional info, articles that you think may help the developer should be added here.
