### ISSUE TITLE
[TASK]Implement live counter 

### ISSUE THREAD

**Issue by Rethakgetse-Manaka** [COS301-SE-2024/occupi#269]
**Task Request**
Implement the live counter using centrifugo for the real time counter.

- [ ] Setup docker files
- [ ] Setup config.json file
- [ ] Run the server and test counter

@Rethakgetse-Manaka , please tick off as you complete each task by clicking on the task you are done with in this comment

**Additional info**
Any additional info, articles that you think may help the developer should be added here.

**Comment by waveyboym** [comment]
@Rethakgetse-Manaka please may you close issues when you are done so we can clean our backlog thank you :)
