### ISSUE TITLE
[TASK]Fix Appearance Settings

### ISSUE THREAD

**Issue by KamogeloMoeketse** [COS301-SE-2024/occupi#272]
**Task Request**

- [ ] Please allow the user to select a theme and store the theme in secure storage
- [ ] If system theme is selected, use useColorScheme.
- [ ] Store Accent colour in secure storage and apply to navbar as well as all other incomplete accent color components.

@KamogeloMoeketse , please tick off as you complete each task by clicking on the task you are done with in this comment
