### ISSUE TITLE
[TASK] Integtae Ocupancy data with Mobile

### ISSUE THREAD

**Issue by KamogeloMoeketse** [COS301-SE-2024/occupi#286]
**Task Request**

- [ ] Find a better graphing library. (perhaps one with animation)
- [ ] Pull data from model endpoint
- [ ] Display occupancy data on graph

@KamogeloMoeketse , please tick off as you complete each task by clicking on the task you are done with in this comment
