### ISSUE TITLE
[TASK]Integrate Analytics

### ISSUE THREAD

**Issue by KamogeloMoeketse** [COS301-SE-2024/occupi#395]
**Task Request**

Integrate the User stats for the logged in user on mobile.
This includes:

- [x] User Total Hours 
- [x] User Average Hours
- [x] Peak
- [x] Arrival and Departure times
- [x] In Office rate

@KamogeloMoeketse , please tick off as you complete each task by clicking on the task you are done with in this comment

**Additional info**
Any additional info, articles that you think may help the developer should be added here.
