### ISSUE TITLE
[TASK] Show graphs for analytics

### ISSUE THREAD

**Issue by KamogeloMoeketse** [COS301-SE-2024/occupi#396]
**Task Request**
Show appropriate graph data for analytics from #395
These should show when the touchable opacity for the stat is clicked.
 
- [x] Line graph for average hours
- [x] Comparative Line graph for arrival and departure times
- [x] Donut pie graph for In Office rate
- [x] Show all daata for peak hours

@KamogeloMoeketse , please tick off as you complete each task by clicking on the task you are done with in this comment

**Additional info**
Any additional info, articles that you think may help the developer should be added here.
