### ISSUE TITLE
[TASK]Fixes for web

### ISSUE THREAD

**Issue by Tinashe-Austin** [COS301-SE-2024/occupi#401]
**Task Request**

- [ ] Fix the Sidenav
- [ ] Add components to the sidenav and remove the employees tab from the tabcomonent
- [ ] fix buttons and other small issues

<@Tinashe-Austin>, please tick off as you complete each task by clicking on the task you are done with in this comment

**Additional info**
Any additional info, articles that you think may help the developer should be added here.
