### ISSUE TITLE
[TASK]: Writeup logic for api, tests and document

### ISSUE THREAD

**Issue by waveyboym** [COS301-SE-2024/occupi#7]
**Task Request**

- [x] Define api routes and document routes/endpoints
- [x] Define tests
- [x] Setup docker and reverse proxy
- [x] Define golang docs

@waveyboym , please tick off as you complete each task by clicking on the task you are done with in this comment

**Additional info**
Any additional info, articles that you think may help the developer should be added here.
1. https://github.com/Aminkhn/gofiber-mongodb-jwt-redis_rest_api
2. https://blog.stackademic.com/building-a-secure-api-with-golang-42b563d42c0d
3. https://dev.to/shaggyrec/run-a-golang-nginx-and-react-app-in-docker-59kn
