### ISSUE TITLE
[TASK] API docs

### ISSUE THREAD

**Issue by KamogeloMoeketse** [COS301-SE-2024/occupi#93]
**Task Request**

- [x] Update api usage documnetation
- [x] Update example post bodies
- [x] Update example returns
- [ ] Link contents to relevant sections

@Rethakgetse-Manaka , please tick off as you complete each task by clicking on the task you are done with in this comment
