### ISSUE TITLE
[TASK] Mobile Unit Testing

### ISSUE THREAD

**Issue by KamogeloMoeketse** [COS301-SE-2024/occupi#97]
**Task Request**

- [ ] Separate components into their own files
- [ ] Unit tests for componenents
- [ ] Unit tests for pages

@KamogeloMoeketse , please tick off as you complete each task by clicking on the task you are done with in this comment
