### ISSUE TITLE
[TASK] Mobile Integration Testing

### ISSUE THREAD

**Issue by KamogeloMoeketse** [COS301-SE-2024/occupi#98]
**Task Request**

- [ ] Integration test for book-room
- [x] Integration test for view-rooms
- [x] Integration test for checkin
- [x] Integration test for cancel-booking
- [x] Integration test for login
- [x] Integration test for register

@u21631532 , please tick off as you complete each task by clicking on the task you are done with in this comment

**Comment by u21631532** [comment]
![image](https://github.com/COS301-SE-2024/occupi/assets/96811395/8146af6f-8098-41b0-9fbd-16995c920bad)
Please note, all api endpoints have been commented out and will need to be revisited for full integration testing
